# SPDX-License-Identifier: GPL-3.0-or-later
#
# AstraOS Live — systemd-boot fallback entry (UEFI)
# Uses initramfs-linux-fallback.img (more drivers, useful if main boot fails).

title   AstraOS Live (x86_64) — fallback initramfs
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/intel-ucode.img
initrd  /%INSTALL_DIR%/boot/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux-fallback.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL%
