[options]
Architecture = auto
Color
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional

[core]
Server = https://archlinux.mirrors.ovh.net/archlinux/$repo/os/$arch

[extra]
Server = https://archlinux.mirrors.ovh.net/archlinux/$repo/os/$arch

[multilib]
Server = https://archlinux.mirrors.ovh.net/archlinux/$repo/os/$arch
